### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/1


### Find a particular user with a given email
GET http://localhost:3000/auth?email=aaa@aaa.com

### Delete a particular user with a given id
DELETE  http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email":"aaa@aaa.com"
}